# Generated by Django 5.0.7 on 2024-08-01 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgame', '0002_userinfo_useractivity_delete_choice_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
